export interface BlogPost {
  slug: string;
  date: string;
  tag: string;
  tagColor: string;
  title: string;
  excerpt: string;
  readTime: string;
  content: string[];  // array of paragraphs / markdown-like sections
}

export const POSTS_ZH: BlogPost[] = [
  {
    slug: "deepseek-rag-enterprise-ai",
    date: "2025-03-15",
    tag: "AI",
    tagColor: "#b44aff",
    title: "DeepSeek + RAG：如何构建企业级 AI 客服系统",
    excerpt: "深入解析我们为客户构建 AI 客服的完整技术方案——从知识库搭建到向量检索，再到流式响应的工程实现。",
    readTime: "8 min",
    content: [
      "## 为什么企业需要 AI 客服",
      "传统客服系统面临三大痛点：人力成本高、响应速度慢、知识覆盖不全。一个训练有素的客服代表需要 2-3 个月的培训期，而且无法 24 小时在线。AI 客服可以在毫秒级别响应，同时覆盖企业全部知识库内容。",
      "但纯粹的大模型（如 GPT、DeepSeek）存在一个关键问题：幻觉。它会编造不存在的产品信息或政策细节。这就是 RAG（Retrieval-Augmented Generation）的价值所在——让 AI 基于真实数据回答问题。",
      "## 架构设计",
      "我们的企业 AI 客服系统采用三层架构：",
      "**1. 知识层（Knowledge Layer）**\n将企业文档（产品手册、FAQ、政策文件）切分为 500 字的文本块，使用 sentence-transformers 生成向量嵌入，存储到 ChromaDB 向量数据库。支持增量更新，新文档上传后 5 分钟内可被检索。",
      "**2. 检索层（Retrieval Layer）**\n用户提问后，系统同时执行关键词检索和向量相似度检索（混合检索），取 Top-5 最相关的文本块作为上下文。混合检索比纯向量检索的准确率高 23%。",
      "**3. 生成层（Generation Layer）**\n将检索到的上下文注入 DeepSeek 的 System Prompt，加上对话历史，调用 API 生成回答。使用 SSE（Server-Sent Events）实现流式输出，用户看到逐字生成的效果。",
      "## 关键技术细节",
      "**DeepSeek API 调用**\nDeepSeek 兼容 OpenAI 协议，用 openai Python SDK 即可调用。我们选择 deepseek-chat 模型，在性价比和质量之间取得最佳平衡。",
      "```python\nfrom openai import OpenAI\nclient = OpenAI(\n    api_key=settings.DEEPSEEK_API_KEY,\n    base_url=\"https://api.deepseek.com\"\n)\nresponse = client.chat.completions.create(\n    model=\"deepseek-chat\",\n    messages=[{\"role\": \"system\", \"content\": system_prompt}, ...],\n    stream=True\n)\n```",
      "**System Prompt 设计**\n好的 System Prompt 是 AI 客服质量的关键。我们的 Prompt 结构：品牌人设 + 行为规则 + 上下文注入 + 回答格式约束。限制回答长度在 2-3 句，避免冗长。",
      "**流式响应**\n前端使用 fetch + ReadableStream 解析 SSE 数据流，每收到一个 token 就追加到消息气泡中。配合打字机光标动画，体验非常自然。",
      "## 效果数据",
      "部署到客户系统后的真实数据：\n- 响应时间：首字 < 500ms，完整回答 < 3s\n- 准确率：92%（基于人工抽检 500 条对话）\n- 客户满意度：从 78% 提升到 94%\n- 人工客服工单减少 65%",
      "## 总结",
      "DeepSeek + RAG 是当前构建企业 AI 客服的最佳实践。DeepSeek 提供高性价比的推理能力，RAG 确保回答基于事实。关键是要做好知识库的维护和 Prompt 的迭代优化——这不是一次性工作，而是持续的过程。",
    ],
  },
  {
    slug: "nextjs-16-tailwind-4-tech-choice",
    date: "2025-03-01",
    tag: "前端",
    tagColor: "#00e5ff",
    title: "Next.js 16 + Tailwind CSS 4：我们的技术选型思考",
    excerpt: "为什么我们选择 Next.js 16 App Router + Tailwind CSS 4 作为前端主力框架？从性能、DX 到 SEO 全方位分析。",
    readTime: "6 min",
    content: [
      "## 技术选型的底层逻辑",
      "每一次技术选型都是在回答一个问题：在当前团队规模、项目类型和交付要求下，什么组合能让我们又快又好地交付？作为一个 AI 驱动的精英小团队，我们的选型标准是：AI 友好度 > 开发效率 > 生态成熟度 > 性能上限。",
      "## 为什么是 Next.js 16",
      "**App Router 是未来**\nNext.js 16 的 App Router 支持 React Server Components、嵌套布局、流式渲染和并行路由。这意味着首屏加载只发送必要的 HTML + 最小 JS bundle，Lighthouse 性能分数轻松 90+。",
      "**SSR/SSG 灵活切换**\n客户官网用 SSG（静态生成）获得极致速度，SaaS 后台用 SSR（服务端渲染）保证数据实时性。一个框架覆盖两种场景。",
      "**API Routes = 轻量后端**\n简单的接口（如 AI 聊天、表单提交）直接用 Next.js API Routes，不需要额外搭后端服务。Vercel 上部署后自动变成 Serverless Function。",
      "**AI 生成友好**\n我们用 AI 辅助编码，Next.js 的文件系统路由和约定式结构让 AI 生成的代码结构一致、可预测。比起自由度过高的 SPA 框架，Next.js 的约束反而是优势。",
      "## 为什么是 Tailwind CSS 4",
      "**v4 的革命性变化**\nTailwind CSS 4 完全重写了引擎，用 Rust 构建的 Oxide 引擎比 v3 快 10 倍。支持原生 CSS 变量主题，不再需要 tailwind.config.js 里定义所有 token。",
      "**CSS-in-JS 的灵活 + 零运行时**\n原子化类名意味着零运行时开销，同时 @apply 和 CSS 变量给了我们 CSS-in-JS 级别的灵活性。暗色主题只需要切换 CSS 变量，不需要切换整套类名。",
      "**AI 辅助写样式的最佳搭档**\n让 AI 写 Tailwind 类名比写原始 CSS 准确率高得多。类名是「声明式」的（\"make it blue\" → `text-blue-500`），AI 能准确映射自然语言到样式。",
      "## 被我们淘汰的方案",
      "- **Nuxt.js**：Vue 生态，我们团队 React 经验更深\n- **Remix**：优秀但生态不如 Next.js 成熟\n- **styled-components**：运行时 CSS-in-JS，性能不如 Tailwind\n- **Chakra UI / shadcn**：组件库限制了定制空间，我们更倾向从零搭建设计系统",
      "## 总结",
      "Next.js 16 + Tailwind CSS 4 是 2025 年前端项目的黄金组合。它给了我们 SSR/SSG 的灵活性、内置 API 能力、极致性能和 AI 友好的开发体验。如果你的项目需要 SEO、需要高性能、需要快速迭代，这就是最优选择。",
    ],
  },
  {
    slug: "zero-employee-ai-workflow",
    date: "2025-02-15",
    tag: "工程化",
    tagColor: "#3b82f6",
    title: "零员工公司的 AI 工作流：5 倍效率的秘密",
    excerpt: "公开我们的 AI 辅助开发流水线——从需求分析到代码生成、测试、部署，每一步如何用 AI 提效。",
    readTime: "10 min",
    content: [
      "## 一个人 = 一个团队？",
      "凌柒科技没有传统意义上的「员工」。我们的模式是：每个人都是独立的全栈贡献者，AI 工具链承担了产品经理、初级开发、测试工程师和文档编写的大部分工作。这不是科幻——这是我们每天的日常。",
      "## 完整的 AI 工作流",
      "**阶段 1：需求分析（AI 占比 70%）**\n客户通过 AI 助手描述需求，系统自动提取关键信息：项目类型、核心功能、技术偏好、预算范围。AI 生成结构化的需求文档初稿，人类审核和补充。\n\n传统方式：3-5 次会议，1-2 周 → AI 方式：1 次对话 + 1 次确认，1-2 天",
      "**阶段 2：方案设计（AI 占比 50%）**\n基于需求文档，AI 生成：\n- 信息架构和页面列表\n- 线框图描述（文字版）\n- 技术方案（框架选型、数据库设计、API 结构）\n- 工期和成本估算\n\n人类负责创意决策、视觉方向和客户沟通。",
      "**阶段 3：UI 设计（AI 占比 30%）**\n这一步 AI 辅助较少，因为高质量设计仍然需要人类审美判断。AI 的角色：\n- 生成配色方案建议\n- 批量生成组件变体\n- 检查设计一致性（间距、字号、颜色使用）",
      "**阶段 4：编码开发（AI 占比 80%）**\n这是 AI 发挥最大价值的环节。我们的流程：\n1. 人类写 Prompt 描述组件/功能需求\n2. AI（Claude/Cursor）生成代码\n3. 人类审查、测试、微调\n4. AI 辅助写单元测试\n5. 提交并自动部署\n\n一个熟练的人 + AI 的开发速度约等于 3-5 个中级开发者。",
      "**阶段 5：测试与部署（AI 占比 60%）**\n- AI 生成测试用例和边界条件\n- 自动化 CI/CD：代码推送后自动构建、测试、部署\n- AI 审查代码变更，标记潜在风险\n- Vercel Preview Deploy 让客户实时查看进展",
      "## 工具链一览",
      "| 环节 | 工具 | 用途 |\n|------|------|------|\n| 编码 | Claude Code / Cursor | AI 辅助编码 |\n| 版本控制 | GitHub | 代码管理 + CI/CD |\n| 部署 | Vercel | 自动部署 + Preview |\n| 设计 | Figma | UI 设计协作 |\n| 沟通 | 微信 / Slack | 客户沟通 |\n| 项目管理 | Linear | 任务追踪 |\n| 文档 | Notion | 知识库 + 文档 |",
      "## 真实数据对比",
      "以一个中等复杂度的企业官网项目为例：\n\n| 指标 | 传统团队（5人） | AI 工作流（1人） |\n|------|----------------|------------------|\n| 开发周期 | 6-8 周 | 1.5-2 周 |\n| 人力成本 | ¥80,000-120,000 | ¥15,000-25,000 |\n| 代码质量 | 中等 | 高（AI 审查） |\n| 文档完整度 | 60% | 95%（AI 生成） |",
      "## 局限性",
      "AI 工作流不是万能的：\n- 复杂的业务逻辑设计仍需人类深度思考\n- 高度创意的视觉设计 AI 还做不好\n- 遗留系统对接需要大量人工排查\n- AI 生成的代码需要严格审查，不能盲目信任",
      "## 总结",
      "AI 不会取代开发者，但「会用 AI 的开发者」会取代「不会用 AI 的开发者」。我们的实践证明，一个人 + AI 工具链可以达到传统 5 人团队的产出。关键不在于工具本身，而在于如何设计工作流让 AI 发挥最大价值。",
    ],
  },
  {
    slug: "saas-in-3-weeks",
    date: "2025-02-01",
    tag: "案例",
    tagColor: "#f59e0b",
    title: "从 0 到上线：3 周交付企业级 SaaS 平台",
    excerpt: "复盘一个真实项目——如何在 3 周内完成需求分析、UI 设计、全栈开发和部署上线。",
    readTime: "7 min",
    content: [
      "## 项目背景",
      "客户是一家跨境电商公司，需要一个内部运营管理平台。核心需求：\n- 订单管理：导入/查看/处理订单\n- 库存管理：多仓库库存追踪\n- 数据看板：销售额、退货率、库存周转率\n- 权限管理：管理员 / 运营 / 仓库三种角色\n\n预算：¥35,000 | 工期要求：1 个月内上线",
      "## 第 1 周：需求 + 设计",
      "**Day 1-2：需求梳理**\n通过 2 小时视频会议 + AI 助手辅助，完成需求文档。AI 自动生成了信息架构、页面列表和数据库 ER 图初稿。\n\n**Day 3-5：UI 设计**\n使用 Figma 设计 12 个核心页面。采用暗色主题 + 数据密集型布局。设计系统基于 Tailwind CSS token，确保设计稿到代码零偏差。\n\n**Day 6-7：客户确认**\n客户审核设计稿，提出 3 处修改。一天内完成修改并确认。",
      "## 第 2 周：核心开发",
      "**技术栈选择**\n- 前端：Next.js 16 + Tailwind CSS 4 + TanStack Table\n- 后端：Next.js API Routes + Prisma ORM\n- 数据库：PostgreSQL（Supabase 托管）\n- 认证：NextAuth.js + JWT\n- 部署：Vercel\n\n**开发节奏**\n每天产出 2-3 个完整页面（AI 辅助编码 + 人工审查）。核心模块开发顺序：认证系统 → 订单管理 → 库存管理 → 数据看板。",
      "## 第 3 周：打磨 + 上线",
      "**Day 15-17：功能完善**\n- Excel 批量导入订单\n- 多仓库切换逻辑\n- 数据看板图表（ECharts）\n- 响应式适配（支持平板操作）\n\n**Day 18-19：测试**\n- AI 生成测试用例 50+\n- 手动测试核心流程\n- 性能优化（首屏 < 1.5s）\n\n**Day 20-21：部署上线**\n- Vercel 生产部署\n- 自定义域名 + SSL\n- 数据库迁移 + 初始数据导入\n- 客户培训（1 小时视频教学）",
      "## 最终交付",
      "- 12 个功能页面\n- 3 种用户角色权限\n- Excel 导入/导出\n- 实时数据看板\n- 完整的 API 文档\n- 部署在 Vercel + Supabase\n\n客户反馈：「比预期快一周，质量超出预期。」",
      "## 关键经验",
      "1. **设计系统先行**：统一的 token 让 AI 生成的代码风格一致\n2. **选择托管服务**：Supabase + Vercel 省去了运维时间\n3. **AI 写 CRUD**：标准的增删改查让 AI 来写，人类专注业务逻辑\n4. **客户每日可见**：Vercel Preview 让客户每天看到进展，减少返工",
    ],
  },
  {
    slug: "taro-cross-platform-miniprogram",
    date: "2025-01-15",
    tag: "小程序",
    tagColor: "#22c55e",
    title: "Taro 跨平台小程序开发实战：一套代码三端运行",
    excerpt: "使用 Taro 框架实现微信、支付宝、抖音三端小程序同步开发的最佳实践与踩坑指南。",
    readTime: "9 min",
    content: [
      "## 为什么选 Taro",
      "客户需要同时上线微信、支付宝和抖音小程序。如果分别开发三套代码，工作量 x3，维护成本也 x3。Taro（京东开源）让我们用 React 语法写一套代码，编译到三个平台。",
      "对比其他方案：\n- **uni-app**：Vue 生态，我们团队 React 更熟\n- **原生开发**：三端三套代码，维护成本太高\n- **Taro**：React 语法 + 跨端编译 + 社区活跃",
      "## 项目结构设计",
      "```\nsrc/\n  pages/           # 页面组件\n  components/      # 共享组件\n  services/        # API 调用层\n  stores/          # 状态管理 (Zustand)\n  utils/           # 工具函数\n  platform/        # 平台差异化代码\n    weapp.ts       # 微信专属逻辑\n    alipay.ts      # 支付宝专属逻辑\n    tt.ts          # 抖音专属逻辑\n```\n\n关键原则：90% 的代码是跨平台的，10% 的平台差异用条件编译处理。",
      "## 踩坑记录",
      "**坑 1：样式差异**\n微信和支付宝的默认样式不同。解决方案：写一个 reset.scss 统一基础样式，所有尺寸用 rpx 单位。\n\n**坑 2：支付 API 差异**\n微信用 `wx.requestPayment`，支付宝用 `my.tradePay`，参数格式完全不同。解决方案：封装统一的 `pay()` 函数，内部根据 `process.env.TARO_ENV` 分发。\n\n**坑 3：分享机制不同**\n微信支持 `onShareAppMessage`，抖音需要额外的分享组件。解决方案：封装 `ShareButton` 组件，内部适配。\n\n**坑 4：登录流程差异**\n微信 `wx.login` 拿 code → 后端换 openid。支付宝 `my.getAuthCode` 流程类似但参数不同。抖音 `tt.login` 又是一套。统一封装 `auth()` 方法。",
      "## 性能优化",
      "小程序有严格的包大小限制（微信主包 2MB）。我们的优化策略：\n- **分包加载**：核心页面放主包，非核心功能分包\n- **图片压缩**：所有图片用 WebP + CDN\n- **按需引入**：组件库按需引入，不整包导入\n- **数据预加载**：页面跳转前预请求下一页数据",
      "## 云开发集成",
      "使用微信云开发作为后端：\n- 云函数处理业务逻辑\n- 云数据库存储数据\n- 云存储托管图片和文件\n\n优势：无需额外服务器，按量付费，自动扩容。对于中小型小程序，云开发是最经济的选择。",
      "## 总结",
      "Taro 跨平台开发的 ROI 非常高：一套代码覆盖三端，开发成本节省 60%，维护成本节省 70%。但要做好平台差异的抽象封装——这是跨端开发成功的关键。建议在项目初期就建立平台差异化的代码规范。",
    ],
  },
  {
    slug: "dark-theme-design-system",
    date: "2025-01-01",
    tag: "设计",
    tagColor: "#06b6d4",
    title: "暗色主题设计系统：从 Token 到组件库的搭建",
    excerpt: "分享我们如何构建一套完整的暗色主题设计系统——CSS 变量体系、Tailwind 配置与组件规范。",
    readTime: "5 min",
    content: [
      "## 为什么是暗色主题",
      "我们的品牌定位是「科技感 + 专业感」。暗色主题天然传达这种调性：深色背景让荧光色（cyan、purple）的发光效果更突出，也减少长时间阅读的视觉疲劳。越来越多的科技产品默认采用暗色主题——Linear、Vercel、Raycast 都是优秀案例。",
      "## 设计 Token 体系",
      "所有颜色、间距、字号定义为 CSS Custom Properties，而不是硬编码值：\n\n```css\n:root {\n  /* 背景层级 */\n  --bg-deep: #050a15;\n  --bg-primary: #0a1122;\n  --bg-secondary: #111b2e;\n  --bg-elevated: #182340;\n  \n  /* 文字层级 */\n  --text-primary: #e8ecf4;\n  --text-secondary: #8a95a8;\n  --text-muted: #4a5568;\n  \n  /* 荧光色 */\n  --neon-cyan: #00e5ff;\n  --neon-purple: #b44aff;\n  --neon-blue: #3b82f6;\n  \n  /* 边框 */\n  --border-subtle: rgba(255,255,255,0.06);\n  --border-default: rgba(255,255,255,0.1);\n}\n```\n\n这套 token 的设计原则：\n1. **层级清晰**：背景从深到浅 4 级，文字从亮到暗 3 级\n2. **对比度达标**：主文字与主背景的对比度 > 7:1（WCAG AAA）\n3. **荧光点缀**：cyan 做主交互色，purple 做次要强调，不滥用",
      "## Tailwind CSS 配置",
      "将 token 映射到 Tailwind 的 theme 配置中，让类名语义化：\n\n```typescript\n// tailwind.config.ts\ntheme: {\n  extend: {\n    colors: {\n      bg: {\n        deep: 'var(--bg-deep)',\n        primary: 'var(--bg-primary)',\n        secondary: 'var(--bg-secondary)',\n        elevated: 'var(--bg-elevated)',\n      },\n      text: {\n        primary: 'var(--text-primary)',\n        secondary: 'var(--text-secondary)',\n        muted: 'var(--text-muted)',\n      },\n      neon: {\n        cyan: 'var(--neon-cyan)',\n        purple: 'var(--neon-purple)',\n      }\n    }\n  }\n}\n```\n\n使用时：`bg-bg-deep text-text-primary border-border-subtle`——类名即设计语义。",
      "## 组件规范",
      "基于 token 构建的核心组件：\n\n**卡片（Card）**\n- 背景：`bg-bg-secondary/30` + `backdrop-blur-md`（毛玻璃效果）\n- 边框：`border-border-subtle`，hover 时变为 `border-neon-cyan/20`\n- 阴影：不用 box-shadow，用 border-top 颜色变化模拟发光\n\n**按钮（Button）**\n- Primary：`bg-neon-cyan text-bg-deep`，hover 加 glow shadow\n- Secondary：透明背景 + `border-border-default`，hover 文字变 cyan\n- Ghost：纯文字，hover 加背景色\n\n**输入框（Input）**\n- 背景：比周围卡片略深\n- Focus：`border-neon-cyan/30` + `shadow-[0_0_0_3px_rgba(0,229,255,0.06)]`\n- 浮动标签动画：聚焦时标签上移缩小",
      "## 动效规范",
      "- **页面过渡**：`fadeInUp`（opacity 0→1 + translateY 20→0），300ms\n- **hover 效果**：200ms ease-out，不用弹簧动画（太 playful）\n- **发光效果**：box-shadow 脉冲，2s 周期，用于 CTA 按钮\n- **加载骨架**：pulse 动画，bg-secondary → bg-elevated 渐变",
      "## 总结",
      "暗色主题设计系统的核心是 Token → Config → Component 三层映射。Token 定义视觉语言，Tailwind Config 桥接设计和代码，Component 规范保证一致性。一套好的设计系统让 AI 生成的代码天然符合品牌规范——这对我们的 AI 工作流至关重要。",
    ],
  },
];

export const POSTS_EN: BlogPost[] = [
  {
    slug: "deepseek-rag-enterprise-ai",
    date: "2025-03-15",
    tag: "AI",
    tagColor: "#b44aff",
    title: "DeepSeek + RAG: Building Enterprise AI Customer Service",
    excerpt: "A deep dive into our complete technical approach for building AI customer service — from knowledge base construction to vector retrieval and streaming responses.",
    readTime: "8 min",
    content: [
      "## Why Enterprises Need AI Customer Service",
      "Traditional customer service faces three pain points: high labor costs, slow response times, and incomplete knowledge coverage. A well-trained support agent needs 2-3 months of training and can't be available 24/7. AI customer service responds in milliseconds while covering the entire enterprise knowledge base.",
      "But pure LLMs (GPT, DeepSeek) have a critical problem: hallucination. They fabricate product details or policy information. That's where RAG (Retrieval-Augmented Generation) comes in — grounding AI responses in real data.",
      "## Architecture Design",
      "Our enterprise AI customer service system uses a three-layer architecture:",
      "**1. Knowledge Layer**\nEnterprise documents (product manuals, FAQs, policy files) are chunked into 500-character segments, embedded using sentence-transformers, and stored in ChromaDB. Supports incremental updates — new documents become searchable within 5 minutes.",
      "**2. Retrieval Layer**\nWhen a user asks a question, the system performs both keyword search and vector similarity search (hybrid retrieval), selecting the Top-5 most relevant chunks as context. Hybrid retrieval is 23% more accurate than pure vector search.",
      "**3. Generation Layer**\nRetrieved context is injected into DeepSeek's System Prompt along with conversation history. SSE (Server-Sent Events) enables streaming output for a natural typing effect.",
      "## Key Technical Details",
      "**DeepSeek API Integration**\nDeepSeek is OpenAI-compatible, callable via the openai Python SDK. We use the deepseek-chat model for the best balance of cost and quality.",
      "```python\nfrom openai import OpenAI\nclient = OpenAI(\n    api_key=settings.DEEPSEEK_API_KEY,\n    base_url=\"https://api.deepseek.com\"\n)\nresponse = client.chat.completions.create(\n    model=\"deepseek-chat\",\n    messages=[{\"role\": \"system\", \"content\": system_prompt}, ...],\n    stream=True\n)\n```",
      "**System Prompt Design**\nA well-crafted System Prompt is the key to AI quality. Our structure: brand persona + behavior rules + context injection + response format constraints. We limit responses to 2-3 sentences to avoid verbosity.",
      "**Streaming Response**\nThe frontend uses fetch + ReadableStream to parse SSE data streams, appending each token to the message bubble. Combined with a typing cursor animation, the experience feels natural.",
      "## Performance Results",
      "Real data after deployment:\n- Response time: first token < 500ms, complete answer < 3s\n- Accuracy: 92% (based on manual review of 500 conversations)\n- Customer satisfaction: improved from 78% to 94%\n- Human support tickets reduced by 65%",
      "## Summary",
      "DeepSeek + RAG is the current best practice for enterprise AI customer service. DeepSeek provides cost-effective inference, RAG ensures factual accuracy. The key is maintaining the knowledge base and iterating on prompts — this is an ongoing process, not a one-time setup.",
    ],
  },
  {
    slug: "nextjs-16-tailwind-4-tech-choice",
    date: "2025-03-01",
    tag: "Frontend",
    tagColor: "#00e5ff",
    title: "Next.js 16 + Tailwind CSS 4: Our Tech Stack Decision",
    excerpt: "Why we chose Next.js 16 App Router + Tailwind CSS 4 as our primary frontend framework. A comprehensive analysis covering performance, DX, and SEO.",
    readTime: "6 min",
    content: [
      "## The Logic Behind Tech Choices",
      "Every tech choice answers one question: given our team size, project types, and delivery requirements, what combination lets us ship fast and ship well? As an AI-driven elite team, our criteria: AI-friendliness > dev efficiency > ecosystem maturity > performance ceiling.",
      "## Why Next.js 16",
      "**App Router is the Future**\nNext.js 16's App Router supports React Server Components, nested layouts, streaming rendering, and parallel routes. First-load sends only necessary HTML + minimal JS bundle, easily scoring 90+ on Lighthouse.",
      "**Flexible SSR/SSG**\nClient corporate sites use SSG for maximum speed, SaaS dashboards use SSR for real-time data. One framework covers both scenarios.",
      "**API Routes = Lightweight Backend**\nSimple endpoints (AI chat, form submissions) use Next.js API Routes directly — no separate backend needed. Deployed on Vercel, they automatically become Serverless Functions.",
      "**AI Generation Friendly**\nWe use AI-assisted coding extensively. Next.js's file-system routing and convention-over-configuration structure means AI-generated code is consistent and predictable. Compared to overly-flexible SPA frameworks, Next.js's constraints are actually an advantage.",
      "## Why Tailwind CSS 4",
      "**v4's Revolutionary Changes**\nTailwind CSS 4 completely rewrote its engine. The Rust-built Oxide engine is 10x faster than v3. Native CSS variable theming — no more defining every token in tailwind.config.js.",
      "**CSS-in-JS Flexibility + Zero Runtime**\nUtility classes mean zero runtime overhead, while @apply and CSS variables give CSS-in-JS level flexibility. Dark theme switching only needs CSS variable changes, not entire class swaps.",
      "**Best Partner for AI-Assisted Styling**\nAI writing Tailwind classes is far more accurate than writing raw CSS. Classes are declarative ('make it blue' maps to `text-blue-500`), and AI maps natural language to styles reliably.",
      "## Alternatives We Considered",
      "- **Nuxt.js**: Vue ecosystem, our team has deeper React experience\n- **Remix**: Excellent but less mature ecosystem than Next.js\n- **styled-components**: Runtime CSS-in-JS, lower performance than Tailwind\n- **Chakra UI / shadcn**: Component libraries limit customization; we prefer building design systems from scratch",
      "## Summary",
      "Next.js 16 + Tailwind CSS 4 is the golden combo for 2025 frontend projects. SSR/SSG flexibility, built-in API capability, peak performance, and AI-friendly DX. If your project needs SEO, needs performance, needs fast iteration — this is the optimal choice.",
    ],
  },
  {
    slug: "zero-employee-ai-workflow",
    date: "2025-02-15",
    tag: "Engineering",
    tagColor: "#3b82f6",
    title: "Zero-Employee AI Workflow: The Secret to 5x Efficiency",
    excerpt: "An open look at our AI-assisted development pipeline — from requirements analysis to code generation, testing, and deployment.",
    readTime: "10 min",
    content: [
      "## One Person = One Team?",
      "LingQi Tech has no traditional 'employees.' Our model: every person is an independent full-stack contributor, and AI toolchain handles most of the product manager, junior developer, test engineer, and documentation writer work. This isn't sci-fi — it's our daily reality.",
      "## The Complete AI Workflow",
      "**Stage 1: Requirements Analysis (AI: 70%)**\nClients describe needs through our AI assistant, which automatically extracts: project type, core features, tech preferences, budget range. AI generates a structured requirements doc draft; humans review and refine.\n\nTraditional: 3-5 meetings, 1-2 weeks. AI way: 1 conversation + 1 confirmation, 1-2 days.",
      "**Stage 2: Solution Design (AI: 50%)**\nBased on requirements, AI generates:\n- Information architecture and page list\n- Wireframe descriptions (text-based)\n- Technical proposal (framework selection, database design, API structure)\n- Timeline and cost estimates\n\nHumans handle creative decisions, visual direction, and client communication.",
      "**Stage 3: UI Design (AI: 30%)**\nAI assistance is lower here — high-quality design still requires human aesthetic judgment. AI's role:\n- Generate color scheme suggestions\n- Batch-create component variants\n- Check design consistency (spacing, font sizes, color usage)",
      "**Stage 4: Coding (AI: 80%)**\nThis is where AI delivers maximum value:\n1. Human writes prompt describing component/feature requirements\n2. AI (Claude/Cursor) generates code\n3. Human reviews, tests, fine-tunes\n4. AI helps write unit tests\n5. Commit and auto-deploy\n\nOne skilled person + AI ≈ 3-5 mid-level developers.",
      "**Stage 5: Testing & Deployment (AI: 60%)**\n- AI generates test cases and edge conditions\n- Automated CI/CD: push triggers build, test, deploy\n- AI reviews code changes, flags potential risks\n- Vercel Preview Deploy lets clients see progress in real-time",
      "## Toolchain Overview",
      "| Phase | Tool | Purpose |\n|-------|------|--------|\n| Coding | Claude Code / Cursor | AI-assisted development |\n| Version Control | GitHub | Code management + CI/CD |\n| Deploy | Vercel | Auto-deploy + Preview |\n| Design | Figma | UI design collaboration |\n| Communication | WeChat / Slack | Client communication |\n| Project Mgmt | Linear | Task tracking |\n| Documentation | Notion | Knowledge base + docs |",
      "## Real Comparison Data",
      "For a medium-complexity corporate website:\n\n| Metric | Traditional Team (5) | AI Workflow (1) |\n|--------|---------------------|------------------|\n| Timeline | 6-8 weeks | 1.5-2 weeks |\n| Labor Cost | $11,000-17,000 | $2,000-3,500 |\n| Code Quality | Medium | High (AI-reviewed) |\n| Documentation | 60% | 95% (AI-generated) |",
      "## Limitations",
      "AI workflow isn't a silver bullet:\n- Complex business logic still needs deep human thinking\n- Highly creative visual design is still beyond AI\n- Legacy system integration requires extensive manual investigation\n- AI-generated code needs strict review — never trust blindly",
      "## Summary",
      "AI won't replace developers, but 'developers who use AI' will replace 'developers who don't.' Our practice proves that one person + AI toolchain can match a traditional 5-person team's output. The key isn't the tools themselves, but designing workflows that maximize AI's value.",
    ],
  },
  {
    slug: "saas-in-3-weeks",
    date: "2025-02-01",
    tag: "Case Study",
    tagColor: "#f59e0b",
    title: "Zero to Production: Enterprise SaaS in 3 Weeks",
    excerpt: "A retrospective on a real project — how we completed requirements, UI design, full-stack development, and deployment in just 3 weeks.",
    readTime: "7 min",
    content: [
      "## Project Background",
      "Client: a cross-border e-commerce company needing an internal operations platform. Core requirements:\n- Order management: import/view/process orders\n- Inventory management: multi-warehouse stock tracking\n- Data dashboard: revenue, return rate, inventory turnover\n- Role-based access: admin / operations / warehouse\n\nBudget: $5,000 | Deadline: within 1 month",
      "## Week 1: Requirements + Design",
      "**Day 1-2: Requirements**\n2-hour video call + AI assistant produced a structured requirements doc. AI auto-generated information architecture, page list, and database ER diagram draft.\n\n**Day 3-5: UI Design**\n12 core pages designed in Figma. Dark theme with data-dense layouts. Design system based on Tailwind CSS tokens for zero design-to-code deviation.\n\n**Day 6-7: Client Approval**\nClient reviewed mockups, requested 3 changes. Completed within one day.",
      "## Week 2: Core Development",
      "**Tech Stack**\n- Frontend: Next.js 16 + Tailwind CSS 4 + TanStack Table\n- Backend: Next.js API Routes + Prisma ORM\n- Database: PostgreSQL (Supabase hosted)\n- Auth: NextAuth.js + JWT\n- Deploy: Vercel\n\n**Development Pace**\n2-3 complete pages per day (AI-assisted coding + manual review). Build order: auth → orders → inventory → dashboard.",
      "## Week 3: Polish + Launch",
      "**Day 15-17: Feature Completion**\n- Excel bulk order import\n- Multi-warehouse switching\n- Dashboard charts (ECharts)\n- Responsive tablet support\n\n**Day 18-19: Testing**\n- AI generated 50+ test cases\n- Manual core flow testing\n- Performance optimization (first paint < 1.5s)\n\n**Day 20-21: Deployment**\n- Vercel production deploy\n- Custom domain + SSL\n- Database migration + seed data\n- Client training (1-hour video walkthrough)",
      "## Final Delivery",
      "- 12 functional pages\n- 3 user roles with permissions\n- Excel import/export\n- Real-time data dashboard\n- Complete API documentation\n- Deployed on Vercel + Supabase\n\nClient feedback: 'A week ahead of schedule, quality exceeded expectations.'",
      "## Key Takeaways",
      "1. **Design system first**: Unified tokens keep AI-generated code style-consistent\n2. **Choose managed services**: Supabase + Vercel eliminate ops overhead\n3. **AI writes CRUD**: Standard data operations are perfect for AI; humans focus on business logic\n4. **Daily client visibility**: Vercel Preview lets clients see daily progress, reducing rework",
    ],
  },
  {
    slug: "taro-cross-platform-miniprogram",
    date: "2025-01-15",
    tag: "Mini Programs",
    tagColor: "#22c55e",
    title: "Cross-Platform Mini Program Development with Taro",
    excerpt: "Best practices and lessons learned building WeChat, Alipay, and Douyin mini programs from a single codebase using Taro.",
    readTime: "9 min",
    content: [
      "## Why Taro",
      "Client needed simultaneous launch on WeChat, Alipay, and Douyin. Developing three separate codebases means 3x work and 3x maintenance. Taro (open-sourced by JD.com) lets us write React-syntax code that compiles to all three platforms.",
      "Compared to alternatives:\n- **uni-app**: Vue ecosystem, our team knows React better\n- **Native development**: Three codebases, unsustainable maintenance\n- **Taro**: React syntax + cross-platform compilation + active community",
      "## Project Structure",
      "```\nsrc/\n  pages/           # Page components\n  components/      # Shared components\n  services/        # API layer\n  stores/          # State management (Zustand)\n  utils/           # Utilities\n  platform/        # Platform-specific code\n    weapp.ts       # WeChat-specific\n    alipay.ts      # Alipay-specific\n    tt.ts          # Douyin-specific\n```\n\nKey principle: 90% of code is cross-platform, 10% platform differences handled via conditional compilation.",
      "## Gotchas & Solutions",
      "**Gotcha 1: Style Differences**\nWeChat and Alipay have different default styles. Solution: write a reset.scss to unify base styles, use rpx units for all dimensions.\n\n**Gotcha 2: Payment API Differences**\nWeChat uses `wx.requestPayment`, Alipay uses `my.tradePay` with completely different parameter formats. Solution: wrap a unified `pay()` function that dispatches based on `process.env.TARO_ENV`.\n\n**Gotcha 3: Share Mechanisms**\nWeChat supports `onShareAppMessage`, Douyin needs an additional share component. Solution: wrap a `ShareButton` component with internal platform adaptation.\n\n**Gotcha 4: Login Flow Differences**\nWeChat `wx.login`, Alipay `my.getAuthCode`, Douyin `tt.login` — all different. Unified under an `auth()` method.",
      "## Performance Optimization",
      "Mini programs have strict bundle size limits (WeChat main package: 2MB). Our strategies:\n- **Subpackage loading**: Core pages in main package, non-critical features in subpackages\n- **Image compression**: All images in WebP + CDN\n- **Tree shaking**: Component library imported on-demand\n- **Data prefetching**: Pre-request next page data before navigation",
      "## Cloud Development Integration",
      "Using WeChat Cloud Development as backend:\n- Cloud functions for business logic\n- Cloud database for storage\n- Cloud storage for images and files\n\nAdvantage: No separate server needed, pay-per-use, auto-scaling. For small-to-medium mini programs, cloud development is the most economical choice.",
      "## Summary",
      "Taro cross-platform development has excellent ROI: one codebase covers three platforms, saving 60% development cost and 70% maintenance cost. But proper abstraction of platform differences is critical — this is the key to successful cross-platform development. Establish platform differentiation coding standards early in the project.",
    ],
  },
  {
    slug: "dark-theme-design-system",
    date: "2025-01-01",
    tag: "Design",
    tagColor: "#06b6d4",
    title: "Dark Theme Design System: From Tokens to Components",
    excerpt: "How we built a complete dark theme design system — CSS variable architecture, Tailwind configuration, and component standards.",
    readTime: "5 min",
    content: [
      "## Why Dark Theme",
      "Our brand positioning is 'tech + professional.' Dark themes naturally convey this: dark backgrounds make neon colors (cyan, purple) glow effects more prominent, and reduce visual fatigue during extended reading. More tech products default to dark themes — Linear, Vercel, Raycast are excellent examples.",
      "## Design Token System",
      "All colors, spacing, and font sizes are defined as CSS Custom Properties, not hardcoded values:\n\n```css\n:root {\n  /* Background hierarchy */\n  --bg-deep: #050a15;\n  --bg-primary: #0a1122;\n  --bg-secondary: #111b2e;\n  --bg-elevated: #182340;\n  \n  /* Text hierarchy */\n  --text-primary: #e8ecf4;\n  --text-secondary: #8a95a8;\n  --text-muted: #4a5568;\n  \n  /* Neon accents */\n  --neon-cyan: #00e5ff;\n  --neon-purple: #b44aff;\n  --neon-blue: #3b82f6;\n}\n```\n\nDesign principles:\n1. **Clear hierarchy**: 4 background levels (deep to light), 3 text levels (bright to dim)\n2. **Contrast compliance**: Primary text vs primary background > 7:1 (WCAG AAA)\n3. **Neon accents**: Cyan for primary interactions, purple for secondary emphasis — used sparingly",
      "## Tailwind CSS Configuration",
      "Map tokens to Tailwind's theme config for semantic class names:\n\n```typescript\ntheme: {\n  extend: {\n    colors: {\n      bg: {\n        deep: 'var(--bg-deep)',\n        primary: 'var(--bg-primary)',\n        secondary: 'var(--bg-secondary)',\n        elevated: 'var(--bg-elevated)',\n      },\n      text: {\n        primary: 'var(--text-primary)',\n        secondary: 'var(--text-secondary)',\n        muted: 'var(--text-muted)',\n      },\n      neon: {\n        cyan: 'var(--neon-cyan)',\n        purple: 'var(--neon-purple)',\n      }\n    }\n  }\n}\n```\n\nUsage: `bg-bg-deep text-text-primary border-border-subtle` — class names are design semantics.",
      "## Component Standards",
      "Core components built on tokens:\n\n**Card**\n- Background: `bg-bg-secondary/30` + `backdrop-blur-md` (glassmorphism)\n- Border: `border-border-subtle`, hover changes to `border-neon-cyan/20`\n- Shadow: No box-shadow; use border-top color change to simulate glow\n\n**Button**\n- Primary: `bg-neon-cyan text-bg-deep`, hover adds glow shadow\n- Secondary: Transparent + `border-border-default`, hover text turns cyan\n- Ghost: Text only, hover adds background\n\n**Input**\n- Background: Slightly darker than surrounding card\n- Focus: `border-neon-cyan/30` + `shadow-[0_0_0_3px_rgba(0,229,255,0.06)]`\n- Floating label animation: label moves up and shrinks on focus",
      "## Motion Standards",
      "- **Page transitions**: `fadeInUp` (opacity 0-1 + translateY 20-0), 300ms\n- **Hover effects**: 200ms ease-out, no spring animations (too playful)\n- **Glow effects**: box-shadow pulse, 2s cycle, for CTA buttons\n- **Loading skeletons**: pulse animation, bg-secondary to bg-elevated gradient",
      "## Summary",
      "The core of a dark theme design system is the Token - Config - Component three-layer mapping. Tokens define the visual language, Tailwind Config bridges design and code, Component standards ensure consistency. A good design system means AI-generated code naturally follows brand guidelines — critical for our AI workflow.",
    ],
  },
];

export function getPostBySlug(slug: string, locale: string): BlogPost | undefined {
  const posts = locale === "zh" ? POSTS_ZH : POSTS_EN;
  return posts.find((p) => p.slug === slug);
}

export function getAllSlugs(): string[] {
  return POSTS_ZH.map((p) => p.slug);
}
